model:
  model_name: "Qwen/Qwen3-4B-Instruct-2507"
  max_seq_length: 4096
  lora_r: 32
  lora_alpha: 64

training:
  num_train_epochs: 3
  per_device_train_batch_size: 2
  gradient_accumulation_steps: 4
  learning_rate: 0.0002
  warmup_ratio: 0.03

raft_data:
  oracle_percentage: 0.8
  num_distractors: 4
  judge_model: "gpt-4.1"

retrieval:
  embedding_model: "BAAI/bge-m3"
  use_reranker: true
  reranker_model: "BAAI/bge-reranker-v2-m3"

evaluation:
  compute_faithfulness: true
  compute_answer_relevance: true
  compute_rouge: true

system:
  project_name: "MSRS-RAFT"
  use_wandb: true  # Set to true for experiment tracking